apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lhomx7sf8-python 
  janus-idp.io/tekton: lhomx7sf8-python
  backstage.io/kubernetes-id: lhomx7sf8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lhomx7sf8-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml